#!/bin/bash
#PURPOSE: re-apply changes across very similar files (eg: changes to boilerplate)
temp="$(mktemp -t -d "git-redo.XXXXXXXXXX")"
[ -n "$temp" ] || exit 1
_cleanup(){
	rm -rf "$temp"
}
trap _cleanup INT EXIT

if [ ! "${1#--filter=}" = "$1" ]; then
	filter="${1#--filter=}"
	shift
fi

if [ $# -ne 2 ]; then
	echo "Usage: git redo <file with changes> <file to re-apply changes to>" >&2
	exit 1
fi
changes_from="$1"
changes_to="$2"

function filter(){
	if [ -n "$filter" ]; then
		bash -c "$filter"
	else
		cat
	fi
}

git cat "$changes_from" | filter > "$temp/A" || exit 1
cat "$changes_from" | filter > "$temp/B" || exit 1
merge -L "$changes_to" -L "$changed_from" "$changes_to" "$temp/A" "$temp/B"
exit "$?"
